name: campus_care
description: A Flutter mobile app for campus food ordering with Supabase backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  supabase_flutter: ^1.10.4
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  fluttertoast: ^8.2.2
  razorpay_flutter: ^1.3.5
  intl: ^0.18.1
  flutter_svg: ^2.0.5
  uuid: ^3.0.7
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  shared_preferences: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  font_awesome_flutter: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env